name: This-Month-In-Reactive-Graph

on:
  push:
    branches: [ main ]
    paths:
      - "src/**"
      - "book.css"
      - "book.toml"
      - ".github/workflows/book.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "src/**"
      - "book.css"
      - "book.toml"
      - ".github/workflows/book.yml"

env:
  CARGO_TERM_COLOR: always

jobs:
  book:
    name: Book
    runs-on: ubuntu-latest
    steps:
      - name: VCS Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install mdBook
        uses: dtolnay/install@master
        with:
          crate: mdbook

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: 'latest'

      - name: Install mdbook-admonish
        uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: mdbook-admonish

      - name: Install mdbook-mermaid
        uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: mdbook-mermaid

      - name: Install mdbook-tera
        uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: mdbook-tera
          locked: false

      - name: Install mdbook-rss
        uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: mdbook-rss

      - name: Install mdbook-preprocessor-graphql-playground
        uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: mdbook-preprocessor-graphql-playground

      - name: Build Book
        working-directory: .
        run: mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
          cname: this-month-in.reactive-graph.io
          # destination_dir: book
